### ISSUE TITLE
Remote Build Failing - mime-types dependency

### ISSUE THREAD

**Issue by chrishol** [iron-io/iron_worker_ruby_ng#159]
Error:

```
/task/__gems__/gems/bundler-1.3.5/lib/bundler/runtime.rb:33:in `block in setup': You have already activated mime-types 2.0, but your Gemfile requires mime-types 1.25. Using bundle exec may solve this. (Gem::LoadError)
    from /task/__gems__/gems/bundler-1.3.5/lib/bundler/runtime.rb:19:in `setup'
    from /task/__gems__/gems/bundler-1.3.5/lib/bundler.rb:120:in `setup'
    from /task/__gems__/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /task/__builder__.rb:45:in `<top (required)>'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from __runner__.rb:213:in `<main>'
```

Stacktrace:

```
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/iron_core-1.0.1/lib/iron_core/iron_logger.rb:50:in `raise_exception'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/iron_core-1.0.1/lib/iron_core/iron_logger.rb:27:in `error'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/iron_worker_ng-1.0.2/lib/iron_worker_ng/client.rb:116:in `codes_create'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/iron_worker_ng-1.0.2/lib/iron_worker_ng/client.rb:18:in `method_missing'
/Users/chrishol/code/hasty-backend/lib/tasks/iron_worker.rake:24:in `upload_worker'
/Users/chrishol/code/hasty-backend/lib/tasks/iron_worker.rake:40:in `block (5 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/bugsnag-1.6.3/lib/bugsnag/rake.rb:27:in `block in bugsnag_define_task'
Tasks: TOP => workers:staging:upload_yelp_cacher
```

A new version of the mime-types gem was just released. Does this need fixing at < 2.0 for now?

**Comment by hanchang** [comment]
I had a bunch of these issues as well, and downgrading from ruby 2.1 to ruby 1.9 as the stack solved my problem.

    # your.worker
    runtime "ruby"
    stack "ruby-1.9"

**Comment by treeder** [comment]
Hey guys, we recommend use the new Docker based workerflow for IronWorker, gets rid of all these issues. 

Blog post: http://blog.iron.io/2015/03/the-new-ironworker-development-workflow.html
Examples repo: https://github.com/iron-io/dockerworker
