### ISSUE TITLE
error using CLI tool to upload java worker (HTTP 404)

### ISSUE THREAD

**Issue by gracklemann** [iron-io/iron_worker_ruby_ng#220]
I am receiving this error when running "iron_worker upload hello". 
I am following the java Hello World example here: http://dev.iron.io/worker/languages/java/
My iron.json file should be correct, as  I am able to push/retrieve messages into an iron queue programatically using the same file. 

Here are my iron_worker and ruby versions:
C:\temp\irontest>iron_worker -v
iron_worker_ruby_ng-1.6.4 (iron_core_ruby-1.0.7)

C:\temp\irontest>ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]

NOTE: I am trying this from Windows, but installed everything on an Ubuntu 14 vm and receive the exact same error. 

Any ideas? 
Thanks!

Here is the error from the CLI output:
```
------> Creating client
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-3.0.6/lib/rest/wrappers/net_http_persistent_wrapper.rb:103:in `get': HTTP 404 Error: Not found (Rest::HttpError)
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-3.0.6/lib/rest/client.rb:127:in `block in get'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-3.0.6/lib/rest/client.rb:151:in `perform_op'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-3.0.6/lib/rest/client.rb:126:in `get'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iron_core-1.0.7/lib/iron_core/client.rb:212:in `get'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iron_worker_ng-1.6.4/lib/iron_worker_ng/api_client.rb:150:in `projects_get'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iron_worker_ng-1.6.4/lib/iron_worker_ng/client.rb:439:in `projects_get'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iron_worker_ng-1.6.4/lib/iron_worker_ng/client.rb:18:in `method_missing'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iron_worker_ng-1.6.4/lib/iron_worker_ng/cli.rb:67:in `client'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iron_worker_ng-1.6.4/lib/iron_worker_ng/cli.rb:82:in `upload'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/iron_worker_ng-1.6.4/bin/iron_worker:124:in `<top (required)>'
	from C:/Ruby22-x64/bin/iron_worker:23:in `load'
	from C:/Ruby22-x64/bin/iron_worker:23:in `<main>'
```

**Comment by gracklemann** [comment]
Issue resolved (thanks @Alexander Shapiotko!). 
I was attempting to use IronMQ v3 token/project IDs.. which are not yet compatible with IronWorker.
